[project]
site_name = "knowledge base"

nav = [
    { "Home" = "index.md" },           
    { "JavaScript" = [
        "java-script/index.md",
        "java-script/standard-built-in-objects.md",
    ] },
    { "SQL" = [
        "sql/index.md",
        {"SQLite" = "sql/sqlite.md"},
    ] },
]

[project.theme]
language = "es"
features = [
    "navigation.tabs"
]



[[project.theme.palette]] 
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"





